import { Profile } from '../types';

export const DEMO_PROFILES: Profile[] = [
  {
    id: 1, adId: 'AD-SEED1000', firstName: 'Nimal', lastName: 'Silva',
    gender: 'MALE', age: 28, religion: 'BUDDHIST', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 174, country: 'Sri Lanka',
    district: 'Colombo', city: 'Colombo', education: "Bachelor's Degree",
    profession: 'Engineer', employedIn: 'Private Sector',
    annualIncome: 'LKR 1,000,000 - 2,000,000',
    aboutMe: 'I am a sincere, family-oriented person looking for a life partner who shares similar values and dreams.',
    partnerExpectations: 'Looking for someone who is kind, educated and family-oriented.',
    fatherOccupation: 'Retired Government Officer', motherOccupation: 'Homemaker',
    siblings: 1, isVerified: true, photoUrl: '', createdAt: '2024-01-01',
  },
  {
    id: 2, adId: 'AD-SEED1001', firstName: 'Kumari', lastName: 'Perera',
    gender: 'FEMALE', age: 25, religion: 'BUDDHIST', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 158, country: 'Sri Lanka',
    district: 'Gampaha', city: 'Negombo', education: "Master's Degree",
    profession: 'Doctor', employedIn: 'Government',
    annualIncome: 'LKR 2,000,000 - 5,000,000',
    aboutMe: 'A dedicated doctor who loves family time and traditional values.',
    partnerExpectations: 'Looking for a well-educated, caring and respectful partner.',
    fatherOccupation: 'Teacher', motherOccupation: 'Nurse',
    siblings: 2, isVerified: true, photoUrl: '', createdAt: '2024-01-02',
  },
  {
    id: 3, adId: 'AD-SEED1002', firstName: 'Sunil', lastName: 'Fernando',
    gender: 'MALE', age: 30, religion: 'HINDU', ethnicity: 'TAMIL',
    civilStatus: 'NEVER_MARRIED', height: 170, country: 'Sri Lanka',
    district: 'Jaffna', city: 'Jaffna', education: "Bachelor's Degree",
    profession: 'Teacher', employedIn: 'Government',
    annualIncome: 'LKR 500,000 - 1,000,000',
    aboutMe: 'A calm and responsible person who values culture and tradition.',
    partnerExpectations: 'Seeking a kind-hearted partner who respects family values.',
    fatherOccupation: 'Farmer', motherOccupation: 'Homemaker',
    siblings: 0, isVerified: false, photoUrl: '', createdAt: '2024-01-03',
  },
  {
    id: 4, adId: 'AD-SEED1003', firstName: 'Priya', lastName: 'Jayasuriya',
    gender: 'FEMALE', age: 26, religion: 'HINDU', ethnicity: 'TAMIL',
    civilStatus: 'NEVER_MARRIED', height: 160, country: 'Sri Lanka',
    district: 'Colombo', city: 'Dehiwala', education: 'Diploma',
    profession: 'IT Professional', employedIn: 'Private Sector',
    annualIncome: 'LKR 1,000,000 - 2,000,000',
    aboutMe: 'Tech-savvy and creative, I enjoy cooking and spending time with family.',
    partnerExpectations: 'Looking for an understanding, ambitious partner.',
    fatherOccupation: 'Business Owner', motherOccupation: 'Teacher',
    siblings: 1, isVerified: true, photoUrl: '', createdAt: '2024-01-04',
  },
  {
    id: 5, adId: 'AD-SEED1004', firstName: 'Rohan', lastName: 'Wickramasinghe',
    gender: 'MALE', age: 32, religion: 'CHRISTIAN', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 176, country: 'Australia',
    district: 'Melbourne', city: 'Melbourne', education: "Master's Degree",
    profession: 'Accountant', employedIn: 'Private Sector',
    annualIncome: 'Above LKR 5,000,000',
    aboutMe: 'Living abroad but keeping Sri Lankan roots close to heart.',
    partnerExpectations: 'Would love to settle down with someone who values family.',
    fatherOccupation: 'Doctor', motherOccupation: 'Homemaker',
    siblings: 2, isVerified: true, photoUrl: '', createdAt: '2024-01-05',
  },
  {
    id: 6, adId: 'AD-SEED1005', firstName: 'Sandya', lastName: 'Bandara',
    gender: 'FEMALE', age: 27, religion: 'CATHOLIC', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 162, country: 'Sri Lanka',
    district: 'Kandy', city: 'Kandy', education: "Bachelor's Degree",
    profession: 'Lawyer', employedIn: 'Private Sector',
    annualIncome: 'LKR 2,000,000 - 5,000,000',
    aboutMe: 'A passionate lawyer who loves music, travel and family gatherings.',
    partnerExpectations: 'Looking for a mature, honest and loving partner.',
    fatherOccupation: 'Retired Government Officer', motherOccupation: 'Teacher',
    siblings: 1, isVerified: false, photoUrl: '', createdAt: '2024-01-06',
  },
  {
    id: 7, adId: 'AD-SEED1006', firstName: 'Kasun', lastName: 'Rathnayake',
    gender: 'MALE', age: 29, religion: 'BUDDHIST', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 172, country: 'Sri Lanka',
    district: 'Matara', city: 'Matara', education: "Bachelor's Degree",
    profession: 'Engineer', employedIn: 'Private Sector',
    annualIncome: 'LKR 1,000,000 - 2,000,000',
    aboutMe: 'Simple, honest and hardworking. Love outdoor activities and family.',
    partnerExpectations: 'Seeking someone warm, caring and family-oriented.',
    fatherOccupation: 'Business Owner', motherOccupation: 'Homemaker',
    siblings: 3, isVerified: true, photoUrl: '', createdAt: '2024-01-07',
  },
  {
    id: 8, adId: 'AD-SEED1007', firstName: 'Dilani', lastName: 'Amarasinghe',
    gender: 'FEMALE', age: 24, religion: 'BUDDHIST', ethnicity: 'SINHALESE',
    civilStatus: 'NEVER_MARRIED', height: 155, country: 'Sri Lanka',
    district: 'Colombo', city: 'Nugegoda', education: "Master's Degree",
    profession: 'Doctor', employedIn: 'Government',
    annualIncome: 'LKR 1,000,000 - 2,000,000',
    aboutMe: 'Young doctor committed to helping others. Loves reading and cooking.',
    partnerExpectations: 'Looking for someone educated, caring and responsible.',
    fatherOccupation: 'Engineer', motherOccupation: 'Teacher',
    siblings: 0, isVerified: true, photoUrl: '', createdAt: '2024-01-08',
  },
];

export const DEMO_USERS: Record<string, { id: number; email: string; password: string; profileId: number }> = {
  'nimal@email.com':  { id: 1, email: 'nimal@email.com',  password: 'password123', profileId: 1 },
  'kumari@email.com': { id: 2, email: 'kumari@email.com', password: 'password123', profileId: 2 },
  'sunil@email.com':  { id: 3, email: 'sunil@email.com',  password: 'password123', profileId: 3 },
  'priya@email.com':  { id: 4, email: 'priya@email.com',  password: 'password123', profileId: 4 },
};
